# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('book', models.ManyToManyField(to='app01.Book')),
            ],
        ),
    ]
